version: '3.5'

services:
  app:
    build: .
    command: npm run dev
    volumes:
      - ./pd_web:/pd_web
      -  /pd_web/node_modules
    ports:
      - 8080:8080
    stdin_open: true
    tty: true
    environment:
      - CHOKIDAR_USEPOLLING=true
      - CHOKIDAR_INTERVAL=1000